// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeSeriesAnalyticsService.Infrastructure.DataAccess.EntityFramework;

#nullable disable

namespace TimeSeriesAnalyticsService.Infrastructure.DataAccess.EntityFramework.Migrations
{
    [DbContext(typeof(TimeSeriesDbContext))]
    [Migration("20260302003752_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeSeriesAnalyticsService.Infrastructure.DataAccess.EntityFramework.Entities.TimeSeriesResultEntity", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("FileName");

                    b.Property<double>("AverageExecutionTimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("AverageExecutionTimeSeconds");

                    b.Property<double>("AverageValue")
                        .HasColumnType("double precision")
                        .HasColumnName("AverageValue");

                    b.Property<double>("DeltaSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("DeltaSeconds");

                    b.Property<DateTimeOffset>("FirstStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("FirstStart");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("MaxValue");

                    b.Property<double>("MedianValue")
                        .HasColumnType("double precision")
                        .HasColumnName("MedianValue");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("MinValue");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("RowCount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("FileName");

                    b.HasIndex("AverageExecutionTimeSeconds");

                    b.HasIndex("AverageValue");

                    b.HasIndex("FirstStart");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("TimeSeriesAnalyticsService.Infrastructure.DataAccess.EntityFramework.Entities.TimeSeriesValueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("Date");

                    b.Property<double>("ExecutionTimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("ExecutionTimeSeconds");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FileName");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("FileName", "Date");

                    b.ToTable("Values", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
